### PR TITLE
Fix emptying of ordered locations

### LINKED ISSUE #214: GPL-671 we need to investigate why the LOCATION_EMPTIED_ACTION events do not seem to exist
**Description**
we need to investigate why the LOCATION_EMPTIED_ACTION events do not seem to exist.
This may not be a problem but 10 locations have been emptied 3 after the events work was deployed but there are no events in the warehouse

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
We need to mimic this action in prod

- create a location
- scan in some labwares
- remove all labwares from location
- check warehouse

### PR DESCRIPTION
**Pull request by JamesGlover**
fixes #214 

delete_all was not working on ordered locations, but isn't actually required.
This change ensures that position is also unset for removed labware, and uses
association.reset to ensure that the lack of labware is correctly reflected
on the location.

- Switch thrubyracer => mini_racer
- Fix bin/setup with no database
- Fix removal of labware from orderd locations
- Simplify labware removal
- Better handle large locations

### CODE REVIEW

**Comment by JamesGlover** [comment]
therubyracer => mini_racer change was necessary to even get labwhere running on my new Mac.

**Comment by JamesGlover** [comment]
Whoops, last minute switch from each to find_each broke the tests, as it triggers a reload of the labwares, so the instances checked in the test aren't the ones getting updated.

**Comment by JamesGlover** [comment]
Comments on the last commit are quite thorough, and explain my decisions. I noticed that the failing test had gone through a few iterations with @stevieing recently, so wanted to explain exactly what my reasoning behind the decision was.

File: app/models/locations/location.rb [hunk 1]
```diff
@@ -171,7 +171,7 @@ def remove_all_labwares(current_user)
     unknown_location = UnknownLocation.get
 
     # set the labwares to have location UnknownLocation rather than null
-    labwares.each do |labware|
+    labwares.find_each do |labware|
       labware.update(location: unknown_location, coordinate: nil)
```
Comment (JamesGlover) [inline app/models/locations/location.rb:175]: This last minute change actually broke some tests. See https://github.com/sanger/labwhere/pull/216/commits/b21faadf164723633b181ecc942da012e78beb01 for the nity-gritty details, and an explanation for why I chose to change the tests, rather than revert this change,

File: Gemfile [hunk 2]
```diff
@@ -12,6 +12,7 @@ gem 'jbuilder', '~> 2.0' # Build JSON APIs with ease. Read more: https://github.
 gem 'jquery-rails' # Use jquery as the JavaScript library
 gem 'jquery-turbolinks'
 gem 'jquery-ui-rails'
+gem 'mini_racer'
 gem 'mysql2'
```
Comment (JamesGlover) [inline Gemfile:16]: Switch from therubyracer to mini_racer as the former depends on an early version of V8 which I couldn't get to compile on Catalina.

File: Gemfile.lock [hunk 3]
```diff
@@ -160,7 +160,7 @@ GEM
     jsonapi-renderer (0.2.2)
     launchy (2.4.3)
       addressable (~> 2.3)
-    libv8 (3.16.14.19)
+    libv8 (8.4.255.0)
     listen (2.10.1)
```
Comment (JamesGlover) [inline Gemfile.lock:164]: See! Major version jump

File: app/lib/utils/dependent_loader.rb [hunk 4]
```diff
@@ -34,5 +34,7 @@ def self.start(table, &block)
         end
       end
     end
+  rescue ActiveRecord::NoDatabaseError
+    # Do nothing. We've probably not created the database yet.
   end
```
Comment (JamesGlover) [inline app/lib/utils/dependent_loader.rb:39]: I couldn't run db:setup as this initialize would run before I had a database.

File: app/models/locations/location.rb [hunk 5]
```diff
@@ -166,20 +166,20 @@ def remove_all_labwares(current_user)
...
     # audit that user emptied the location
-    self.create_audit(current_user, Audit::REMOVED_ALL_ACTION)
+    create_audit(current_user, Audit::REMOVED_ALL_ACTION)
 
-    # copy array of labwares to be deleted (labwares will be empty after delete_all)
-    labwares_copy = labwares.each_with_object([]) { |labware, object| object.append(labware) }
-
-    # soft delete labwares to disconnect from relationships including location
-    labwares.delete_all
+    unknown_location = UnknownLocation.get
```
Comment (JamesGlover) [inline app/models/locations/location.rb:172]: This code is mostly superseded by the chunk below. I just added a labwares.reset further down to ensure the relationship was updated in memory.

**Review by stevieing — APPROVED** [review]

**Review by andrewsparkes — COMMENTED** [review]
Looks good to me
