### PR TITLE
GPL-798 - Prevent parent location from being a building for move locations

### LINKED ISSUE #281: GPL-798: BUG - As a sample management manager I would like to see an error message when I try to move a location into a building
**Describe the bug**
BUG - As a sample management manager I would like to see an error message when I try to move a location into a building as it is not a container.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by BenTopping**
Closes #281 

Changes proposed in this pull request:

*
*
* ...

### CODE REVIEW

File: app/forms/move_location_form.rb [hunk 1]
```diff
@@ -61,7 +61,10 @@ def check_user
   end
 
   def check_parent_location
-    return if parent_location.present?
+    if parent_location.present?
+      errors.add(:parent_location, "cannot be a building") if parent_location.location_type.name == "Building"
```
Comment (stevieing) [inline app/forms/move_location_form.rb:65]: I think this might be better to check if it is a container (something that can store labware) because this would cover building, room, car park etc.

**Review by stevieing — CHANGES_REQUESTED** [review]

File: app/forms/move_location_form.rb (hunk 1 above)
Comment (BenTopping) [reply app/forms/move_location_form.rb:65]: 👍

**Comment by BenTopping** [comment]
Dummy data rake tast needs to be reviewed, location container property is set to True for buildings and sites on local which is incorrect

**Review by stevieing — APPROVED** [review]
